import * as React from 'react';

import { LegalPage } from './LegalPage';

// Generated by https://www.shopify.com/tools/policy-generator and slightly adjusted.
const Policy = `\
Frosty Privacy Policy

This Privacy Policy describes how your personal information is collected, used, and shared when you visit or make a purchase from ${window.location.origin} (the “Site”).

PERSONAL INFORMATION WE COLLECT
When you visit the Site, we automatically collect certain information about your device, including information about your web browser, IP address, time zone, and some of the cookies that are installed on your device. Additionally, as you browse the Site, we collect information about the individual web pages or products that you view, what websites or search terms referred you to the Site, and information about how you interact with the Site. We refer to this automatically-collected information as “Device Information.”

We collect Device Information using the following technologies:

    - “Cookies” are data files that are placed on your device or computer and often include an anonymous unique identifier. For more information about cookies, and how to disable cookies, visit http://www.allaboutcookies.org.
    - “Log files” track actions occurring on the Site, and collect data including your IP address, browser type, Internet service provider, referring/exit pages, and date/time stamps.
    - “User content” are data input by you. These include the content of your fridge and recipes you provide.
${''/*[[INSERT ANY OTHER INFORMATION YOU COLLECT:  OFFLINE DATA, PURCHASED MARKETING DATA/LISTS]]*/}
When we talk about “Personal Information” in this Privacy Policy, we are talking about Device Information and User content.

HOW DO WE USE YOUR PERSONAL INFORMATION?
We use the Device Information that we collect to help us screen for potential risk and fraud (in particular, your IP address), and more generally to improve and optimize our Site (for example, by generating analytics about how our customers browse and interact with the Site, and to assess the success of our marketing and advertising campaigns).
${''/*[[INSERT OTHER USES OF DEVICE INFORMATION, INCLUDING:  ADVERTISING/RETARGETING]]*/}
SHARING YOUR PERSONAL INFORMATION
Finally, we may also share your Personal Information to comply with applicable laws and regulations, to respond to a subpoena, search warrant or other lawful request for information we receive, or to otherwise protect our rights.

DO NOT TRACK
Please note that we do not alter our Site’s data collection and use practices when we see a Do Not Track signal from your browser.

YOUR RIGHTS
If you are a European resident, you have the right to access personal information we hold about you and to ask that your personal information be corrected, updated, or deleted. If you would like to exercise this right, please contact us through the contact information below.

Additionally, if you are a European resident we note that we are processing your information in order to fulfill contracts we might have with you (for example if you make an order through the Site), or otherwise to pursue our legitimate business interests listed above.  Additionally, please note that your information will be transferred outside of Europe, including to Canada and the United States.

DATA RETENTION
When you input data into the Site, we will maintain your information for our records unless and until you ask us to delete this information.

CHANGES
We may update this privacy policy from time to time in order to reflect, for example, changes to our practices or for other operational, legal or regulatory reasons.

CONTACT US
For more information about our privacy practices, if you have questions, or if you would like to make a complaint, please contact us by e-mail at ${process.env.REACT_APP_RESPONSIBLE_EMAIL || 'REACT_APP_RESPONSIBLE_EMAIL NOT SET'} or by mail using the details provided below:

  ${process.env.REACT_APP_RESPONSIBLE_ADDRESS || 'REACT_APP_RESPONSIBLE_ADDRESS NOT SET'}
`;

export interface PrivacyPolicyPageProps {}

export const PrivacyPolicyPage: React.StatelessComponent<PrivacyPolicyPageProps> = props => {
  return (
    <LegalPage>{Policy}</LegalPage>
  );
};
